
export const fields = {
    nimi: 'Nimi',
    taajamaaste: 'Taajama-aste',
    väkiluku: 'Väkiluku',
    väkiluvun_muutos_edellisestä_vuodesta: 'Väkiluvun muutos edellisestä vuodesta',
    alle_15vuotiaiden_osuus_väestöstä: 'Alle 15-vuotiaiden osuus väestöstä',
    n1564_vuotiaiden_osuus_väestöstä: '15-16-vuotiaiden osuus väestöstä',
    yli_64vuotiaiden_osuus_väestöstä: 'Yli 64-vuotiaiden osuus väestöstä',
    ruotsinkielisten_osuus_väestöstä: 'Ruotsinkielisten osuus väestöstä',
    ulkomaan_kansalaisten_osuus_väestöstä: 'Ulkomaan kansalaisten osuus väestöstä',
    syntyneiden_enemmyys_henkilöä: 'Syntyneiden enemmyys',
    kuntien_välinen_muuttovoittotappio_henkilöä: 'Kuntien välinen muuttovoittotappio',
    perheiden_lukumäärä: 'Perheiden lukumäärä',
    asuntokuntien_lukumäärä: 'Asuntokuntien lukumäärä',
    rivi_ja_pientaloissa_asuvien_asuntokuntien_osuus: 'Rivi ja pientaloissa asuvien asuntokuntien osuus',
    vuokraasunnoissa_asuvien_asuntokuntien_osuus: 'Vuokra-asunnoissa asuvien asuntokuntien osuus',
    vähintään_keskiasteen_tutkinnon_suorittaneiden_osuus: 'Vähintään keskiasteen tutkinnon suorittaneiden osuus',
    korkeaasteen_tutkinnon_suorittaneiden_osuus: 'Korkea-asteen tutkinnon suorittaneiden osuus',
    alueella_asuvan_työllisen_työvoiman_määrä: 'Alueella asuvan työllisen työvoiman määrä',
    työllisyysaste: 'Työllisyysaste',
    asuinkunnassaan_työssäkäyvien_osuus: 'Asuinkunnassaa työssäkäyvien osuus',
    työttömien_osuus_työvoimasta: 'Työttömien osuus työvoimasta',
    eläkeläisten_osuus_väestöstä: 'Eläkeläisten osuus väestöstä',
    taloudellinen_huoltosuhde: 'Taloudellinen huoltosuhde',
    kunnassa_olevien_työpaikkojen_lukumäärä: 'Kunnassa olevien työpaikkojen lukumäärä',
    alkutuotannon_työpaikkojen_osuus: 'Alkutuotannon työpaikkojen osuus',
    jalostuksen_työpaikkojen_osuus: 'Jalostuksen työpaikkojen osuus',
    palvelujen_työpaikkojen_osuus: 'Palvelujen työpaikkojen osuus',
    vuosikate_euroaasukas: 'Vuosikate euroa/asukas',
    lainakanta_euroaasukas: 'Lainakanta euroa/asukas',
    konsernin_lainakanta_euroaasukas: 'Konsernin lainakanta euroa/asukas',
    opetus_ja_kulttuuritoiminta_yhteensä_nettokäyttökustannukset: 'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset',
    sosiaali_ja_terveystoiminta_yhteensä_nettokäyttökustannukset: 'Sosiaali- ja terveystoimina yhteensä, nettokäyttökustannukset'
}
