
export const units = {
    nimi: '',
    taajamaaste: '%',
    väkiluku: '',
    väkiluvun_muutos_edellisestä_vuodesta: '%',
    alle_15vuotiaiden_osuus_väestöstä: '%',
    n1564_vuotiaiden_osuus_väestöstä: '%',
    yli_64vuotiaiden_osuus_väestöstä: '%',
    ruotsinkielisten_osuus_väestöstä: '%',
    ulkomaan_kansalaisten_osuus_väestöstä: '%',
    syntyneiden_enemmyys_henkilöä: '',
    kuntien_välinen_muuttovoittotappio_henkilöä: '',
    perheiden_lukumäärä: '',
    asuntokuntien_lukumäärä: '',
    rivi_ja_pientaloissa_asuvien_asuntokuntien_osuus: '%',
    vuokraasunnoissa_asuvien_asuntokuntien_osuus: '%',
    vähintään_keskiasteen_tutkinnon_suorittaneiden_osuus: '%',
    korkeaasteen_tutkinnon_suorittaneiden_osuus: '%',
    alueella_asuvan_työllisen_työvoiman_määrä: '',
    työllisyysaste: '%',
    asuinkunnassaan_työssäkäyvien_osuus: '%',
    työttömien_osuus_työvoimasta: '%',
    eläkeläisten_osuus_väestöstä: '%',
    taloudellinen_huoltosuhde: '%',
    kunnassa_olevien_työpaikkojen_lukumäärä: '',
    alkutuotannon_työpaikkojen_osuus: '%',
    jalostuksen_työpaikkojen_osuus: '%',
    palvelujen_työpaikkojen_osuus: '%',
    vuosikate_euroaasukas: '€/asukas',
    lainakanta_euroaasukas: '€/asukas',
    konsernin_lainakanta_euroaasukas: '€/asukas',
    opetus_ja_kulttuuritoiminta_yhteensä_nettokäyttökustannukset: '€',
    sosiaali_ja_terveystoiminta_yhteensä_nettokäyttökustannukset: '€'
}
